baseurl: /starter
permalink: pretty
markdown: rdiscount
defaults:
  -
    scope:
      path: "_posts"
    values:
      published: false
prose:
  rooturl: ''
  siteurl: 'http://prose.github.io/starter/'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'media'
  metadata:
    "_posts":
      - name: "published"
        field:
          element: "hidden"
          value: true
      - name: "title"
        field:
          element: "text"
          labeL: "title"
    "_data":
      - name: "published"
        field:
          element: "hidden"
          value: true
      - name: "title"
        field:
          element: "text"
          labeL: "title"
