baseurl: /starter
permalink: pretty
markdown: rdiscount
prose:
  rooturl: ''
  siteurl: 'http://prose.github.io/starter/'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'media'
  metadata:
    "_posts":
      - name: "Date"
        field:
          element: "hidden"
          value: "CURRENT_DATETIME"
      - name: "tags"
        field:
          element: "multiselect"
          alterable: true