baseurl: /starter
permalink: pretty
markdown: rdiscount
prose:
  rooturl: ''
  siteurl: 'http://prose.github.io/starter/'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'media'
  metadata:
    "_posts":
      - name: "checkbox"
        field:
          element: "checkbox"
          label: "Checkbox label"
          help: "Checkbox help"
          value: true
      - name: "number"
        field:
          element: "number"
          label: "Number label"
          help: "Number help"
          value: 1
          type: "number"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Multiselect"
          placeholder: "Choose Tags"
          options:
            - name: "Bananas"
              value: "bananas"
            - name: "Pears"
              value: "pears"
            - name: "Mangos"
              value: "mangos"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "text"
        field:
          element: "text"
          label: "Text label"
          value: "some value"
      - name: "text"
        field:
          element: "text"
          label: "Another Text label"
          value: "different value"
      - name: "textarea"
        field:
          element: "textarea"
          label: "Textarea label"
          value: ""
