baseurl: /starter
permalink: pretty
markdown: rdiscount
prose:
  rooturl: ''
  siteurl: 'http://prose.github.io/starter/'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'media'
  metadata:
    _posts:
      - name: "lang"
        field:
          element: "select"
          label: "Select language"
          placeholder: "language"
          options:
            - name: "English"
              value: "en"
            - name: "French"
              value: "fr"
