---
published: false
checkbox: true
number: 1
bigtext: null
---





baseurl: /starter
permalink: pretty
markdown: rdiscount
prose:
  rooturl: ''
  siteurl: 'http://prose.github.io/starter/'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'media'
  metadata:
    "":
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          placeholder: "Create a Title for the Menu and Browser"
          value: ""
      - name: "og_title"
        field:
          element: "text"
          label: "Open Graph: Title"
          placeholder: "Create a title for social media"
          value: ""
      - name: "description"
        field:
          element: "textarea"
          label: "Description"
          placeholder: "Create a description for <meta> tags"
          value: ""
      - name: "og_description"
        field:
          element: "textarea"
          label: "Open Graph: Description"
          placeholder: "Create a description for social media"
          value: ""
      - name: "image"
        field:
          element: "text"
          label: "Hero Image"
          placeholder: "Specify a relative URI for a hero image"
          value: ""
      - name: "og_image"
        field:
          element: "text"
          label: "Open Graph: Image"
          placeholder: "Specify a relative URI for a social media image"
          value: ""
      - name: "nav"
        field:
          element: "select"
          label: "Navigation Type"
          placeholder: "Choose a navigation type"
          options:
            - name: "None"
              value: "none"
            - name: "Primary"
              value: "primary"
            - name: "Secondary"
              value: "secondary"
            - name: "Support"
              value: "support"
      - name: "order"
        field:
          element: "select"
          label: "Nav Order"
          placeholder: "Choose this page's order in navigation"
          options:
            - name: "0"
              value: "0"
            - name: "1"
              value: "1"
            - name: "2"
              value: "2"
            - name: "3"
              value: "3"
            - name: "4"
              value: "4"
            - name: "5"
              value: "5"
            - name: "6"
              value: "6"
            - name: "7"
              value: "7"
            - name: "8"
              value: "8"
            - name: "9"
              value: "9"
            - name: "10"
              value: "10"
      - name: "sitemap_exclude"
        field:
          element: "button"
          label: "Exclude from Sitemap"
          help: "Click this button to exclude this page from your sitemap.xml"
          on: "yes"
          off: "no"