baseurl: /starter
permalink: pretty
markdown: rdiscount
prose:
  rooturl: ''
  siteurl: 'http://prose.github.io/starter/'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'media'
  metadata:
    "_posts":
      - name: "Date"
        field:
          element: "hidden"
          value: "CURRENT_DATETIME"
      - name: "publish_date"
        field:
          element: "text"
          placeholder: "dd-mm-yyyy"
      - name: "quotes"
        field:
          element: "text"
      - name: "title"
      - name: "published"
        field:
          element: "button"
          label: "do this or no"
          on: "yes"
          off: "no"
      - name: "big"
        field:
          element: "textarea"
          value: "default"
          label: "Does this work?"
      - name: "select"
        field:
          element: "select"
          value: "foo"
          options:
            - name: "foo"
              value: "foo"
            - name: "bar"
              value: "bar"
